# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: '3.13'

jobs:
  testing:
    uses: quatrope/feets/.github/workflows/tests.yml@a2dfe29002dfee2be7d6ec8b10953d28bbc8a403