# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: '3.11'

jobs:
  testing:
    uses: quatrope/scikit-criteria/.github/workflows/tests.yml@638ddd115072ed319204e177db0a37967c6b298c