# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: Build

on:
  - push
  - pull_request

env:
  default-python: '3.13'

jobs:
  testing:
    uses: quatrope/feets/.github/workflows/tests.yml@11fa1c754967e497003da5664b8f531c0c999553